name: Deploy to Azure

on: push

jobs:
  deploy-infra:
    name: Deploy Infra
    environment: prod
    runs-on: windows-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      # Login to Azure using AAD credentials stored as secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
